[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ProjectXFile"
authors = [{name = "XFile", email = "xFile@xFile.com"}]
dynamic = ["version 1", "description 2"]
